version: 2

project_name: wacli

builds:
  - id: wacli_linux_amd64
    main: ./cmd/wacli
    binary: wacli
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-Wno-error=missing-braces
    flags:
      - -trimpath
    tags:
      - sqlite_fts5
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

  - id: wacli_linux_arm64
    main: ./cmd/wacli
    binary: wacli
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CGO_CFLAGS=-Wno-error=missing-braces
    flags:
      - -trimpath
    tags:
      - sqlite_fts5
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ if eq .Arch "all" }}universal{{ else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums-linux.txt

changelog:
  disable: true
